### ISSUE TITLE
Retry headers handling in retry interceptor

### ISSUE THREAD

**Issue by UDarya** [rybalkinsd/kohttp#105] opened 2019-06-03 09:07 UTC
Please check this article https://developer.mozilla.org/ru/docs/Web/HTTP/%D0%97%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%B8/Retry-After

**Comment by Russiancold** [comment] 2019-08-05 13:41
@rybalkinsd What if the retry-after delay is too large?

**Comment by rybalkinsd** [comment] 2019-08-05 14:22
@Russiancold I think there should a limit, however, it's better to check how it's recommended to handle this delay

**Comment by Russiancold** [comment] 2019-08-05 14:53
I believe that it can varies pretty much, so what about providing `maxRetryTime` field? If the header value overlimits it then it should be passed further to the chain then.

**Comment by rybalkinsd** [comment] 2019-08-05 14:59
In our case, `maxRetryTime` should be somehow aligned with client `connectTimeout`, `readTimeout` and `writeTimeout`

So, it's probably no need to introduce a new variable, but use something based on existing

**Comment by rybalkinsd** [comment] 2019-08-16 11:04
duplicate of #108

**Closed** 2019-08-16 11:03 UTC
Labels: enhancement, good first issue, help wanted
